/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "GeminiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LibsqlAuthToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LibsqlUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Max": {
      "type": "sst.cloudflare.Astro"
      "url": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "ModerationCronHandler": cloudflare.Service
  }
}

import "sst"
export {}