/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AnalyticsCronHandler": import("@cloudflare/workers-types").Service
    "BaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CfAccountId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CfAnalyticsEmail": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CfAnalyticsToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CfSiteTag": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GeminiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LibsqlAuthToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LibsqlUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainDOHost": import("@cloudflare/workers-types").Service
    "Max": {
      "type": "sst.cloudflare.Astro"
      "url": string
    }
    "MigrationToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ModerationCronHandler": import("@cloudflare/workers-types").Service
    "OpenAuthUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}