/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "LibsqlAuthToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LibsqlUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Max": {
      "type": "sst.cloudflare.Astro"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}